### ISSUE TITLE
Password for admin

### ISSUE THREAD

**Issue by SemihDurmaz54** [ilknurmer/Human-Resources-Management-System-Project#1]
what is user id and password?

**Comment by ilknurmer** [comment]
As far as I remember, user id and password were defined in the employee table in project's database. For the database operations, I used MySQL in this project and for the database management, I used PhpMyAdmin web interface of WampServer. I created different tables for my database in the PhpMyAdmin interface. I just added some values to the table and I used JDBC API in order to connect MySQL server database, then I was able to add new employee information to the table from the source code. Therefore, there is not a specific user id and password that I can say to you currently. If you create your own database in localhost and make related connection with JDBC API as it is implemented in openDBconnection() method, you can use any user id and password that you save to employee table in your database.

**Comment by SemihDurmaz54** [comment]
Aa Türkmüşsün, cevap için teşekkürler.

16 Kasım 2020 Pazartesi tarihinde İlknur Meray <notifications@github.com>
yazdı:

**Comment by ilknurmer** [comment]
Rica ederim :)
